apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: kube-cp
spec:
  providerSpec:
    value:
      apiVersion: "libvirt.cluster.k8s.io/v1alpha1"
      kind: "LibvirtMachineProviderSpec"
      spec:
        vcpu: 2
        memoryInGB: 2
        imageURI: /home/carbon/dev/go-projects/src/sigs.k8s.io/cluster-api-provider-libvirt/samples/images/kubernetes-boot-image.qcow2
        userDataURI: /home/carbon/dev/go-projects/src/sigs.k8s.io/cluster-api-provider-libvirt/samples/images/user-data.img


